### ISSUE TITLE
deoplete + django-plus error

### ISSUE THREAD

**Issue by monkoose** [tweekmonster/django-plus.vim#1]
When editing python files in django project(with outside python files all fine) with deoplete autocompletion there is the error appears in insert mode

```
[deoplete] Traceback (most recent call last):
[deoplete]   File "/home/monkoose/.local/share/nvim/site/dein/.dein/rplugin/python3/deoplete/deoplete.py", line 46, in completion_begin
[deoplete]     complete_position, candidates = self.gather_candidates(context)
[deoplete]   File "/home/monkoose/.local/share/nvim/site/dein/.dein/rplugin/python3/deoplete/deoplete.py", line 72, in gather_candidates
[deoplete]     results = self.gather_results(context)
[deoplete]   File "/home/monkoose/.local/share/nvim/site/dein/.dein/rplugin/python3/deoplete/deoplete.py", line 83, in gather_results
[deoplete]     charpos = source.get_complete_position(cont)
[deoplete]   File "/home/monkoose/.local/share/nvim/site/dein/.dein/rplugin/python3/deoplete/sources/django.py", line 29, in get_complete_position
[deoplete]     return self.vim.call('djangoplus#complete', 1, '')
[deoplete]   File "/usr/lib/python3.5/site-packages/neovim/api/nvim.py", line 213, in call
[deoplete]     return self.request('vim_call_function', name, args, **kwargs)
[deoplete]   File "/usr/lib/python3.5/site-packages/neovim/api/nvim.py", line 129, in request
[deoplete]     res = self._session.request(name, *args, **kwargs)
[deoplete]   File "/usr/lib/python3.5/site-packages/neovim/msgpack_rpc/session.py", line 98, in request
[deoplete]     raise self.error_wrapper(err)
[deoplete] neovim.api.nvim.NvimError: b'Vim(return):E117: Unknown function: pythoncomplete#Complete'

```

**Comment by tweekmonster** [comment]
That's strange because that error can't happen if it does exist.  `pythoncomplete#Complete()` is the default completer that's in `$VIMRUNTIME/ftplugin/python.vim`.  This plugin overrides it and defers to it if there's no Django-specific completions.  Could you check the `omnifunc` setting in a non-Django file to see if it's set?  If it is, try calling the function with `echo pythoncomplete#Complete(1, '')`.  Also, try performing a completion with `<c-x><c-o>` to see if you get the same error.

**Comment by monkoose** [comment]
outside a django project 
`omnifunc=jedi#completions`
 
maybe i should turn off vim-jedi? I used it(with manual completions) because deoplete-jedi sometimes fail with large libraries.

`echo pythoncomplete#Complete(1, '')`
`Error: Required vim compiled with +python
Error: Required vim compiled with +python
E117: Unknown function: pythoncomplete#Complete
E15: Invalid expression: pythoncomplete#Complete(1, '')
`

**Comment by tweekmonster** [comment]
I think I see now.  So, it thinks you don't have python 2 installed.  What does `has('python')` show?

**Comment by monkoose** [comment]
I has. But neovim returns `0 to echo has('python')` and `1 to echo has('python3')`. I don't know why.

**Comment by monkoose** [comment]
Ok, i found. I didn't use neovim-python2 i guess.

**Comment by tweekmonster** [comment]
Neovim allows you to run both versions, but you don't need to.  The built-in Python completer apparently only supports Python 2, however.  But, it's still setting the `omnifunc` option.  I can add a check to make sure it doesn't try to use it if Python 2 isn't available.

**Comment by monkoose** [comment]
Ok, all works now as expected. Thank you for your time and help.
