### ISSUE TITLE
Conflicting interaction with emmet-vim

### ISSUE THREAD

**Issue by jdsutherland** [tweekmonster/django-plus.vim#14]
As I understand from https://github.com/mattn/emmet-vim/issues/302, using Emmet with htmldjango filetype requires setting: `autocmd FileType htmldjango EmmetInstall`.

With this autocmd set in vimrc, the following error occurs when opening an html file in a django project (htmldjango): 
`Error detected while processing FileType Auto commands for "htmldjango":`	
`E492: Not an editor command: EmmetInstall`

I noticed that manually doing `:setf html` then `:setf htmldjango` seems to enable Emmet without errors.

I imagine there are others who use this plugin with Emmet. Perhaps there is way to configure Emmet without requiring changing django-plus code?

**Comment by blueyed** [comment]
Looks more like an issue with emmet-vim than django-plus.vim?
Are you loading emmet-vim lazily for e.g. "html" only?
