### ISSUE TITLE
NERDTree/:Sex Error when opening 'new' files

### ISSUE THREAD

**Issue by jjsandee** [tweekmonster/django-plus.vim#3]
When opening a .py file from NERDtree or :Sex not yet in the buffer I get the following error:

`Error detected while processing function djangoplus#detect#filetype..<SNR>108_simple_django_project:`
`line    6:`
`E867: (NFA) Unknown operation '\zo'`
`E68: Invalid character after \z`

After hitting enter it opens the file just fine. It's entirely possible something else is conflicting or I'm missing something obvious. I tend to use NERDTree a lot to switch between files.

**Comment by tweekmonster** [comment]
I'm not getting that error.  I don't normally use NERDtree, so I'm not sure if I can reproduce the issue faithfully.  So, I need you to tell me some things so I can make some guesses:

- Are you on Windows?
- What does `:echo getcwd()` show?
- What does `:echo expand('%')` show?
- Could you add `:echomsg 'XXX' a:filename` above [this line](https://github.com/tweekmonster/django-plus.vim/blob/f35f2c720c269779d868487b1d49a8b839cd632d/autoload/djangoplus/detect.vim#L111) and tell me what it prints?

**Comment by jjsandee** [comment]
Yes, I am on Windows.

The error occurs at other instances, not just in Nerdtree. I have a  script that stored all open files to a session. When I then load that session the error occurs for each file being opened.

`getcwd()` shows shows the current directory open in Nerd Tree which by default is the parent directory of the file currently open in the buffer. And the correct file location when on the opened file buffer. 

`expand('%')` shows NERD_tree_1 (nerd tree names its buffers with increment numbers) when on nerd tree and the filename when on the file buffer.

The echo message shows the correct filename of the file being opened with the correct path.

also the error is repeated twice whenever a file is opened. Once a file has been opened before in the same Vim instance the error doesn't happen again.

**Comment by tweekmonster** [comment]
> shows shows the current directory open in Nerd Tree which by default is the parent directory of the file currently open in the buffer

Right, but what is the path that shows?  That might be what's causing the error if it has pattern-like characters in it.  My guess is it's a path separator with a "z" right after it, like `C:\zorro` or something and it just needs to be escaped.  But, I want confirmation of that to be sure that's all that needs to be fixed.

**Comment by jjsandee** [comment]
Ah yes. The path is `E:\djangoprojects\zo<rest of projectname>`  So it does indeed start with a zo.

**Comment by tweekmonster** [comment]
It should be fixed now.  Let me know if it's resolved.

**Comment by jjsandee** [comment]
Issue is now fixed. Files open without any sort of error.

**Comment by tweekmonster** [comment]
Great, thanks!
