### ISSUE TITLE
filetype check error

### ISSUE THREAD

**Issue by gatspy** [tweekmonster/django-plus.vim#4]
open a template html, the syntax is jinja.
edit a file is not saved on the hard disk,only in the buffer, the syntax is html.

**Comment by tweekmonster** [comment]
What is the error?

**Comment by gatspy** [comment]
I'm sorry , I was wrong. not syntax , it's filetype check error.
open a template html, the filetype as jinja.
edit a file is not saved on the hard disk,only in the buffer, the filetype as html.
Now I'm in command-line mode to manually change the file type

**Comment by tweekmonster** [comment]
Oh okay.  So to be clear, your _default_ filetype is `jinja`, but when you start a new buffer (e.g. with `:e test.html`) and Vim's _current directory_ is a Django project, it doesn't change to the filetype to `htmldjango`?

If that's the case, I think I can fix that.

**Comment by gatspy** [comment]
thank you for your reply. 
After the update, works well.
