### ISSUE TITLE
Getting an error about UltiSnips

### ISSUE THREAD

**Issue by chadgh** [tweekmonster/django-plus.vim#7]
I recently updated django-plus in my vim instance and now I'm getting the following error. I currently have the latest version of UltiSnips and django-plus installed.

> Error detected while processing /home/chadgh/.dotfiles/vim/vim/bundle/django-plus.vim/after/ftplugin/python.vim:
line   15:
E117: Unknown function: UltiSnips#FileTypeChanged

**Comment by blueyed** [comment]
FYI: It was removed in UltiSnips in https://github.com/SirVer/ultisnips/commit/8d77e89d65d5678d3c9b15496e462ab5b8ebd8e9.
